### ISSUE TITLE
Problem in method perform_rest_call: code="101" msg="Invalid frob - did you authenticate?

### ISSUE THREAD

**Issue by alepuzio** [entorb/rememberthemilk#1]
Hi, 
I downloaded your project to trying to get the list of my tasks in RTM but I'm in trouble with authentican

the first tiem I ran the project, I put my api_key and secret in *rememberthemilk.ini* file and I decommeted the code
```
 frob = rtm_getFrob()
 print(f'frob: {frob}')
 print('now open this URL to grant my app access your data:')
 print(rtm_gen_auth_url(frob))
 input("press Enter to continue")
 token = rtm_auth_getToken(frob)

``` 

I obtained my **token** and put this in my *rememberthemilk.ini*. 
Running again the program, I got an error in XML format

`<?xml version='1.0' encoding='UTF-8'?><rsp stat="fail"><err code="101" msg="Invalid frob - did you authenticate?"/></rsp>
`

And I see in stack trace of the error
```

Traceback (most recent call last):
  File "rememberthemilk.py", line 226, in <module>
    token = rtm_auth_getToken(frob)
  File "rememberthemilk.py", line 175, in rtm_auth_getToken
    rtm_assert_rsp_status_ok(reponse_text)
  File "rememberthemilk.py", line 110, in rtm_assert_rsp_status_ok
    assert '<rsp stat="ok">' in reponse_text, print('E: ' + str(reponse_text))
AssertionError: None
```

(pay attention that I put some *print* instruction in the code, then you can have another orw number when you replicate the error)

Do you have any idea?
Can be that RTM has disabled my api_key or secret, because I got thse some years ago with no use?

Thank a lot for your attention

**Comment by entorb** [comment]
Sorry for not responding. I somehow missed your issue.
Today, I refactored the code, please try if it is now clearer.
